### ISSUE TITLE
Eco3x and Pro4x

### ISSUE THREAD

**Issue by ononoohk** [drnick23/drplotter#15]
Eco3x and Pro4x，Two methods, how many fields can 4090 graphics card plant?

**Comment by drnick23** [comment]
Do you mean plots supported? The github README shows expected maximum TB capacities.

**Comment by ononoohk** [comment]
> 你的意思是支持绘图吗？ github README 显示了预期的最大 TB 容量。

14000 and 16400？

**Comment by drnick23** [comment]
Yes
