### ISSUE TITLE
DrSolver not view harvester

### ISSUE THREAD

**Issue by Zebracell** [drnick23/drplotter#21]
![psscreen от 2024-02-17 14-40-55](https://github.com/drnick23/drplotter/assets/123531310/49ba179b-6383-4051-93b2-f8c72542bd46)

drchia start harvester -r
chia_harvester: stopped
chia_harvester: started

**Comment by drnick23** [comment]
In your harvester logs at ~/.chia/mainnet/logs/debug.log, do you see any reports like:

024-02-17T10:47:36.302 harvester drplotter               : INFO     Harvesting 1831 drplots with on disk size 47.69 TiB, after decompression 175.31 eTiB, extra rewards 3.68x

**Comment by drnick23** [comment]
Also, are you using the same token as the one you setup for your harvester? Hsk91....

**Comment by Zebracell** [comment]
yes

> In your harvester logs at ~/.chia/mainnet/logs/debug.log, do you see any reports like:
> 
> 024-02-17T10:47:36.302 harvester drplotter : INFO Harvesting 1831 drplots with on disk size 47.69 TiB, after decompression 175.31 eTiB, extra rewards 3.68x

[debug.log](https://github.com/drnick23/drplotter/files/14318379/debug.log)

**Comment by Zebracell** [comment]
> Also, are you using the same token as the one you setup for your harvester? Hsk91....

i am generate token  and  export DRPLOTTER_CLIENT_TOKEN='[token]'

**Comment by Zebracell** [comment]
and not start classic client chia-blockchain.

**Comment by drnick23** [comment]
No, you need drchia start harvester on a seperate machine that your farmer. The problem for your drchia harvester is here:

2024-02-17T14:49:06.638 harvester harvester               : INFO     Failed to connect to PeerInfo(_ip=IPv4Address('192.168.0.32'), _port=8447)

Maybe you  have a firewall to your farmer at 192.168.0.32?  Currently, the harvester is not able to talk to the farmer.

**Comment by Zebracell** [comment]
> No, you need drchia start harvester on a seperate machine that your farmer. The problem for your drchia harvester is here:
> 
> 2024-02-17T14:49:06.638 harvester harvester : INFO Failed to connect to PeerInfo(_ip=IPv4Address('192.168.0.32'), _port=8447)
> 
> Maybe you have a firewall to your farmer at 192.168.0.32? Currently, the harvester is not able to talk to the farmer.

other harvesters work with this port

**Comment by drnick23** [comment]
can you post your config.yaml from ~/chia/mainnet/config/config.yaml from the same machine drchia is on?

**Comment by drnick23** [comment]
The issue could be here:
 Cannot connect to host 192.168.0.32:8447 ssl:<ssl.SSLContext object at 0x79afc89826c0> [Connect call failed ('192.168.0.32', 8447)]
 which could be the wrong SSL keys for your farmer.  
 
 Do you have a recent official chia harvester installed on the same machine? They introduced some breaking changes to the config file. You may have to delete ~/.chia and then run setup again with drchia init instead.
 
 '''
drchia init
drchia init -c /path/to/your/farmers/ca/certificates (copy the certificates from your farmer machines directory at ~/.chia/mainnet/config/ssl/ca)
'''

**Comment by Zebracell** [comment]
> No, you need drchia start harvester on a seperate machine that your farmer. The problem for your drchia harvester is here:
> 
> 2024-02-17T14:49:06.638 harvester harvester : INFO Failed to connect to PeerInfo(_ip=IPv4Address('192.168.0.32'), _port=8447)
> 
> Maybe you have a firewall to your farmer at 192.168.0.32? Currently, the harvester is not able to talk to the farmer.

in PC i am new install clear chia-blockchain
db synchronization OK
install drplotter
add token and export .bashrc
start drsolver
chia farmer start
drchia start harvester -r


ALL in one PC

In logs at ~/.chia/mainnet/logs/debug.log, 
not see any reports like:
*harvester drplotter*

**Comment by drnick23** [comment]
Currently, you cannot run 

drchia start harvester

on the same machine as a farmer. When you run:

chia start farmer

it loads the chia versions into ram, and when you call drchia after that it will actually start the chia harvester, not drchia since.

You need to chia stop -d all

Then:

drchia start harvester

but setup your config.yaml and in the harvester: section add farmer_peer: with your farmers ip address.

**Comment by Zebracell** [comment]
> Currently, you cannot run
> 
> drchia start harvester
> 
> on the same machine as a farmer. When you run:
> 
> chia start farmer
> 
> it loads the chia versions into ram, and when you call drchia after that it will actually start the chia harvester, not drchia since.
> 
> You need to chia stop -d all
> 
> Then:
> 
> drchia start harvester
> 
> but setup your config.yaml and in the harvester: section add farmer_peer: with your farmers ip address.

farmer only remote PC?

**Comment by drnick23** [comment]
Yes farmer only on remote pc

**Comment by Zebracell** [comment]
if farmer on gigahorse node - not work?

**Comment by drnick23** [comment]
It should be able to connect to GH farmer.

**Comment by Zebracell** [comment]
it not good

**Comment by Zebracell** [comment]
need docker or virtual farmer for this )

**Comment by drnick23** [comment]
I will add eventually support for working with farmer on local machine, but
it is like this by design so you can keep your private keys safe on farmer
machine.

**Comment by Zebracell** [comment]
you need to add information about the mandatory separation of farmer and harvester

**Comment by Zebracell** [comment]
new issues
solver view plot
fbk on farmer = harvester = plot
pca on farmer = plot
harvester:

> 2024-02-18T11:30:08.213 harvester chia.harvester.harvester: INFO     0 classic plots were eligible for farming c5f8d0300c... Found 0 proofs. Time: 0.00001 s. Total 0 classic plots
> 2024-02-18T11:30:08.243 harvester drplotter               : INFO     Harvesting 76 drplots with on disk size 1.78 TiB, after decompression 7.32 eTiB, extra rewards 4.10x
> 2024-02-18T11:30:10.774 harvester chia.harvester.harvester: INFO     _plot_refresh_callback: event started, loaded 0, removed 0, processed 0, remaining 76, duration: 0.00 seconds, total plots: 0
> 2024-02-18T11:30:10.776 harvester chia.plotting.manager   : INFO     Processing 38 drplot files in directory: /media/pvehost/5GT9-p1
> 2024-02-18T11:30:10.776 harvester chia.plotting.manager   : INFO     Processing 38 drplot files in directory: 

but no proof found

chia farm summary

> Farming status: Farming
> Total chia farmed: 0.0
> User transaction fees: 0.0
> Block rewards: 0.0
> Last height farmed: 0
> Local Harvester
>    0 plots of size: 0.000 MiB on-disk, 0.000 MiBe (effective)
 **Remote Harvester for IP: 192.168.0.99
 ** 0 plots of size: 0.000 MiB on-disk, 0.000 MiBe (effective)**
> Plot count for all harvesters: 0
> Total size of plots: 0.000 MiB, 0.000 MiBe (effective)
> Estimated network space: 34.006 EiB
> Expected time to win: Never (no plots)
> Note: log into your key using 'chia wallet show' to see rewards for each key

**Comment by drnick23** [comment]
At the moment the DrChia Harvester only reports regular chia plots to the farmer, so the plot counts you see on the farmer are for chia's official plots only, not the DrPlot counts. The DrPlots are very different and are currently not recognized by your farmer -- this is something to add in a future release.

For now, you can see the # of DrPlots you have here:

 INFO Harvesting 76 drplots with on disk size 1.78 TiB, after decompression 7.32 eTiB, extra rewards 4.10x
 
 If you see that message it is working. You will start getting partial proofs for your pool showing up (you can set pool difficulty to 1, it makes no different to performance of plots), and you can verify with your pool that you are getting the points/plots.

**Comment by Zebracell** [comment]
the solver can be published white ip as gigahorse_recompute_server for multiple farmers?

**Comment by Zebracell** [comment]
farmer1 & farmer2 they prescribe for drchia-harvester white ip farmer3 but all three have different fpc, pca and farmer3 node doesn't know them fpc, pca farmer1 & farmer2
Will it work like this?

**Comment by drnick23** [comment]
I'm not sure I understand all the components of your system. What matters is that the drchia harvester can only connect to one farmer, and currently you can only run one instance of drchia harvester on a machine.

If your system works with the standard chia harvester as a remote harvester that connects to only to one farmer, I expect it should work, but it seems like you have a complex setup.

If you are posting using a language translator, post in your original language and I will use chatgpt to help understand.

**Comment by Zebracell** [comment]
условия
1 три фермера, три разных Pool contract address, Farmer public key
2 общий DRPLOTTER_CLIENT_TOKEN  
3 настраиваем через файл config.yaml 
шаги
фермер 3 открывает порт на роутере 8447
фермер1 и фермер2 в файле config.yaml 
`harvester:
  farmer_peer:
    host: белый ип адрес фермера 3
    port: 8447`
настройка закончена?

**Comment by drnick23** [comment]
OK, I think I understand.

You have 3 farmers machines with 3 different pool contract address and farmer keys. You want Farmer machines 2 and 3 to also connect remotely to farmer machine 1. This doesn't really make sense in chia, since the farmer will submit the proofs to the node and needs the private keys to do that. A farmer needs a node to submit the proofs.

Drplotter doesn't have any farmers of it's own, only the harvester. If you have 3 separate farmers with 3 separate sets of private keys, you will need 3 drchia harvesters and connect one to each farmer. Each drchia harvester will need to read it's own set of drplots made with the keys that work with each farmer.

For example:
Farmer 1 - private keys 1 <--> drchia harvester, drplots with public keys 1
Farmer 2 - private keys 2 <--> drchia harvester, drplots with public keys 2
Farmer 3 - private keys 3 <--> drchia harvester, drplots with public keys 3

You can use the common DRPLOTTER_CLIENT_TOKEN with each harvester, that is no problem.

**Comment by Zebracell** [comment]
если средствами классического клиента (вкладка pooling) подключится на опубликованный порт ноды фермера 3, DrSolver будет работать для таких подключений?

**Comment by Zebracell** [comment]
> OK, I think I understand.
> 
> You have 3 farmers machines with 3 different pool contract address and farmer keys. You want Farmer machines 2 and 3 to also connect remotely to farmer machine 1. This doesn't really make sense in chia, since the farmer will submit the proofs to the node and needs the private keys to do that. A farmer needs a node to submit the proofs.
> 
> Drplotter doesn't have any farmers of it's own, only the harvester. If you have 3 separate farmers with 3 separate sets of private keys, you will need 3 drchia harvesters and connect one to each farmer. Each drchia harvester will need to read it's own set of drplots made with the keys that work with each farmer.
> 
> For example: Farmer 1 - private keys 1 <--> drchia harvester, drplots with public keys 1 Farmer 2 - private keys 2 <--> drchia harvester, drplots with public keys 2 Farmer 3 - private keys 3 <--> drchia harvester, drplots with public keys 3
> 
> You can use the common DRPLOTTER_CLIENT_TOKEN with each harvester, that is no problem.

где в твоей схеме использование GPU & DrSolver фермера три
