### ISSUE TITLE
Rtx 4080

### ISSUE THREAD

**Issue by Motophan** [drnick23/drplotter#4]
rtx 4080s are much more readily available than 4090s at msrp. A 4080 can be had all day for $1000-$1100 in usa, but a 4090 might be $2000+ due to AI people sucking them up instantly. 

I have a 4080 can I contribute data on performance here? Or can you estimate?

**Comment by Motophan** [comment]
I see 24gb, is that a hard req or can 16gb be enough ?
4080 is 16gb

**Comment by drnick23** [comment]
24GB is a currently a hard requirement.

**Comment by Motophan** [comment]
Hear me out for a second. 
it is easier and cheaper to get 2x 4080s than a 4090 currently

If a user had two 4080s would you be able to "raid0" the memory together?

**Comment by drnick23** [comment]
This is technically possible and may make it in a future release, but it won't be for a while and it's not clear if the results will be beneficial yet.
