### ISSUE TITLE
DrSolver Error with local DrServer IP

### ISSUE THREAD

**Issue by rkroelin** [drnick23/drplotter#43]
Receveing the following error when attempting to start DrSolver with the environmental variable DRSERVER_IP_ADDRESS set.

Related to the parsing error you mentioned on discord?
Ubuntu 22.04.4, running a freshly pulled down drplotter_0.10.0_amd64.deb.

DrServer IP set in environment variable DRSERVER_IP_ADDRESS: 100.x.x.x
terminate called after throwing an instance of 'std::invalid_argument'
what():  stoi
Aborted (core dumped)

**Comment by rkroelin** [comment]
drsolver launches fine if you manually specify the default port in the environmental variable.

**Comment by drnick23** [comment]
Thank you, I've update the README to include that you have to specify the port. 

In the next release I'll make it so that the port can be optional.
