### ISSUE TITLE
drsolver - Error code 202

### ISSUE THREAD

**Issue by imba-pericia** [drnick23/drplotter#5]
Wanted to check it on tesla p40.
Solver writes the following lines to the log:
```
[2024-02-01 13:51:22.213] [info] Connecting to server https://solvers>
[2024-02-01 13:51:22.518] [info] Connected to server! (305.24331 ms)
[2024-02-01 13:51:22.520] [info] Solving registration challenge...
[2024-02-01 13:51:22.520] [error] DrError code: 202
```
When start drsolver - `WARN - implement in-place sort`

It's because of p40?

**Comment by drnick23** [comment]
Yes, it's because it's running a pre-ampere architecture.

It's possible to support lower architectures but there will be additional performance loss, and the compute / W won't be competitive.

**Comment by imba-pericia** [comment]
> Yes, it's because it's running a pre-ampere architecture.
> 
Thanks for the quick response.

> It's possible to support lower architectures but there will be additional performance loss, and the compute / W won't be competitive.

Perhaps farmers with 100tb may be satisfied with this.

**Comment by drnick23** [comment]
I don't think the economics of pre-ampere graphics cards will make sense, they are just not as energy efficient and won't be profitable to run.
