### ISSUE TITLE
Minimum  pci-e width and ram for plotter

### ISSUE THREAD

**Issue by revers-back** [drnick23/drplotter#53]
Hi, have a couple of questions 
1. will motherboard with a PCIE 3.0 x 16 slot works for plotting and farming? 
2. will motherboard with a PCIE 4.0 x 8 slot works for plotting and farming? 
3. will be enough 126 GB ram in system for plotting?

**Comment by drnick23** [comment]
1 & 2. PCIE3 x 16 or PCIE 4.0 x 8 will slow down plot times but will work. Expect 10 minute plot times instead of 6 minutes.
3. 126GB should still be enough

**Comment by revers-back** [comment]
Thanks for the answer! Would you please answer a couple more questions. 
1. can drplotter work with two cards on system same time? like if i have 256gb ram and two cards, can i start two independed plotting process? 
2. If i have two 3090 in one system, can i point each one different location for plots? First card will handle 250gb of raw space with eco3 in first pc, and second one card handle 100gb for eco4 plots on another location pc, but two 3090 is in one system
3. This is related to 2. Can solver work on pci-e 3.0 1x bus? Another words, can raiser pci 16x to 1x working propely for solving? 
Thans a lot for this software!

**Comment by revers-back** [comment]
@drnick23 would you please answer?
