### ISSUE TITLE
README.md Profit numbers are too high, 2 times higher than its could be. 

### ISSUE THREAD

**Issue by restot** [drnick23/drplotter#58]
Let's start with this [example](https://github.com/drnick23/drplotter/blob/main/images/pro4x-advantage.png) 16400 plots will be equal to 1623.98 TiB, not 1640 TiB. 
But for me, profits are more important, in this [example ](https://github.com/drnick23/drplotter/blob/main/images/Eco3x-Pro4x-vs-NoSSDC15.png) 
(noSSD) Profits from 11737 will be 0.1790 XCH / day
(Eco3x) Profits from 15135 will be 0.2308 XCH / day
(Pro4x) Profits from 17482 will be 0.2666 XCH / day
That matters a lot considering the higher power consumption using 2x4090 with a total estimated consumption of 945W/h that could cost up 50% of profits or more(or less). 

My point is those examples needed correct estimated XCH profits for all of us considering replot for a new plot format. 
Thank you for your time and effort. @drnick23

**Comment by Smallthing** [comment]
why total estimated consumption is 945w
when you limit it , it will about 330*2=660w 660+ cpu and other ,maybe 750-850w

**Comment by drnick23** [comment]
I have updated the energy / XCH example for the 1.0.3 release here:

https://github.com/drnick23/drplotter/tree/DrServer?tab=readme-ov-file#strategic-efficiency-eco3x-and-pro4x-vs-nossds-c15

This will make it's way into the main github readme soon.
