### ISSUE TITLE
Inquiries on Compatibility and Hardware Requirements

### ISSUE THREAD

**Issue by DAS-WIN** [drnick23/drplotter#6]
Can a Windows version be developed?

If I use a virtual machine to simulate Ubuntu, can the Windows 10 operating system directly farm this file?

Is it necessary to use a 3090 or 4090, or can a 3080 be used as well? Can AMD graphics cards be used?

**Comment by DAS-WIN** [comment]
I'm looking for a less demanding compression tool that still delivers similar compression results. Is there any tool available that has lower hardware requirements? I can manage with the RAM requirements, but needing a graphics card with 24GB of memory is something I can't afford.

**Comment by DAS-WIN** [comment]
I apologize if my sentences are difficult to understand, as I am a Traditional Chinese user. I'm using ChatGPT to facilitate communication.

**Comment by Voodoo-Chia** [comment]
This solution will need 24GB Vram on the GPU, no way around that. Nvidia only.
